
development:
  adapter: postgresql
  encoding: unicode
  database: StartupAssist_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: StartupAssist_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: StartupAssist_production
  pool: 5

